### ISSUE TITLE
Project does not use hosts file specified

### ISSUE THREAD

**Issue by christhomas** [finboxio/docker-dns#1]
I have read through the code and I cannot see anywhere the domain information is loaded from the disk from the file given in the readme instructions.

any explanation for that? perhaps this is unfinished functionality? 

what I did find was a series of hard coded domains in the code instead, I am going to try to get it to work from importing the file from the disk and see how far I can get

**Comment by Yehonal** [comment]
death project?

**Comment by christhomas** [comment]
In the end I ended up making something of my own. This is working pretty well, so @Yehonal, you can try it out and let me know, we use it at my company: https://github.com/christhomas/supervisord-dnsmasq
